blueprint:
  name: OpenEPaperLink 2.6-inch Sensor Data Display
  description: 'Display sensor data and graphs on 2.6" ePaper display tags.
    
    This blueprint is meant for use with the 
    [OpenEPaperLink integration](https://github.com/jonasniesner/open_epaper_link_homeassistant)
    by Jonas Niesner. With this, you can set up automations to use the common 
    2.6" ePaper tags (296x152 pixels) to display various sensor data.
    
    The display can show up to six values at the same time, in the following
    arrangement:
    
    * Two numerical sensor values at the top. By default these are shown in black.
      Each of them can be displayed in red if it is above and/or below a certain threshold.
    
    * Two line graphs in the middle and bottom. Each graph shows a black line 
      with the values of a sensor over a past time period (by default 24h). 
      In addition, the graph can display a thin red line with the values from a
      second sensor over the same time period.
    '
  domain: automation
  
  input:
    tag_entity:
      name: Target display
      description: >
        Data will be displayed on this ePaper tag. The blueprint assumes a
        2.6" tag with 296x152 pixels.
      selector:
        entity:
          multiple: false
    
    triggers:
      name: When to initiate update
      description: >
        This will send new data to the access point. Keep in mind that the tags 
        are refreshed only when they check in with the access point, so it may
        take some time until the display itself is updated. 
      selector:
        trigger:
    
    sensor1:
      name: Top left - Sensor
      description: Values from this sensor will be displayed at the top left.
      selector:
        entity:
    field1_icon:
      name: Top left - Icon
      selector:
        icon:
    
    sensor2:
      name: Top right - Sensor
      description: Values from this sensor will be displayed at the top right.
      selector:
        entity:
    field2_icon:
      name: Top right - Icon
      selector:
        icon:
    
    sensor3:
      name: Middle graph - Sensor
      description: Values from this sensor will be displayed as a black line in the middle graph.
      selector:
        entity:
    field3_icon:
      name: Middle graph - Icon
      selector:
        icon:
    
    sensor5:
      name: Bottom graph - Sensor
      description: Values from this sensor will be displayed as a black line in the bottom graph.
      selector:
        entity:
    field4_icon:
      name: Bottom graph - Icon
      selector:
        icon:
    
  variables:
    tag: !input tag_entity
    sensor1: !input sensor1
    sensor2: !input sensor2
    sensor3: !input sensor3
    sensor5: !input sensor5
    field1_icon: !input field1_icon
    field2_icon: !input field2_icon
    field3_icon: !input field3_icon
    field4_icon: !input field4_icon
    
    layout:
      - &frame
        type: rectangle
        outline: black
        fill: white
        width: 1
      - &icon
        type: icon
        size: 40
        color: black
      - &value
        type: text
        size: 30
        color: black
        anchor: mm
      - &unit
        type: text
        size: 20
        color: black
        anchor: mm
      
      - &frame1
        <<: *frame
        x_start: 0
        y_start: 0
        x_end: 140
        y_end: 49
      - &icon1
        <<: *icon
        x: 10
        y: 8
        value: !input field1_icon
      - &value1
        <<: *value
        x: 100
        y: 14
        value: "{{ states(sensor1) }}"
      
      - &frame2
        <<: *frame
        x_start: 150
        y_start: 0
        x_end: 296
        y_end: 49
      - &icon2
        <<: *icon
        x: 160
        y: 8
        value: !input field2_icon
      - &value2
        <<: *value
        x: 250
        y: 14
        value: "{{ states(sensor2) }}"
      
      - &frame3
        <<: *frame
        x_start: 0
        y_start: 55
        x_end: 296
        y_end: 100
      - &plot3
        type: plot
        x_start: 40
        y_start: 57
        x_end: 280
        y_end: 98
        duration: 86400
        data:
          - entity: !input sensor3
            width: 3
            joint: curve
      
      - &frame4
        <<: *frame
        x_start: 0
        y_start: 105
        x_end: 296
        y_end: 152
      - &plot4
        type: plot
        x_start: 40
        y_start: 107
        x_end: 280
        y_end: 150
        duration: 86400
        data:
          - entity: !input sensor5
            width: 3
            joint: curve
    
  mode: single
  
  action:
    - service: open_epaper_link.drawcustom
      target:
        entity_id: !input tag_entity
      data:
        background: white
        rotate: 0
        ttl: 300
        payload:
          - <<: *frame1
          - <<: *icon1
          - <<: *value1
          - <<: *frame2
          - <<: *icon2
          - <<: *value2
          - <<: *frame3
          - <<: *plot3
          - <<: *frame4
          - <<: *plot4
